class ResponseCodeMappingInFrench {
  static final ResponseCodeMappingInFrench _instant = ResponseCodeMappingInFrench._ctor();

  factory ResponseCodeMappingInFrench(){
    return _instant;
  }

  ResponseCodeMappingInFrench._ctor();

  static const responseCodeMsg = {
    //CASHIER
    "CASHIER_107": "Type d'appareil non fourni.",
    "CASHIER_108": "Type d'agent utilisateur non fourni",
    "CASHIER_601": "Domaine invalide",
    "CASHIER_508": "Informations sur le joueur introuvables",
    "CASHIER_316": "Code de devise invalide",
    "CASHIER_1101": "pays invalide",
    "CASHIER_1502": "Pays non cartographié avec aucune devise.",
    "CASHIER_1121": "Option de paiement introuvable",
    "CASHIER_201": "Requête invalide",
    "CASHIER_1117": "Veuillez fournir un code marchand valide",
    "CASHIER_1105": "type de transaction invalide",
    "CASHIER_962": "Marchand introuvable",
    "CASHIER_308": "Aucune option de paiement disponible.",
    "CASHIER_123": "Frais de traitement introuvables pour le montant demandé",
    "CASHIER_121": "taux de change introuvable",
    "CASHIER_318": "Utiliser le compte n'existe pas",
    "CASHIER_2008": "Limite anonyme dépassée",
    "CASHIER_1213": "Implémentation du fournisseur introuvable.",
    "CASHIER_1214": "Données de paramètres du fournisseur introuvables.",
    "CASHIER_1215": "Configuration de dépôt du fournisseur introuvable.",
    "CASHIER_1216": "Configuration de retrait du fournisseur introuvable.",
    "CASHIER_12015": "Une erreur s'est produite lors de la transaction",
    "CASHIER_1102": "Échec de la mise à jour du portefeuille",
    "CASHIER_309": "Votre paiement a échoué. Veuillez réessayer.",
    "CASHIER_530": "Le code OTP n'est pas valide.",
    "CASHIER_532": "Le nombre maximum de renvois OTP est dépassé",
    "CASHIER_310": "Le numéro de compte doit être le même lors du renvoi OTP",
    "CASHIER_1034": "Veuillez fournir un numéro de mobile valide",
    "CASHIER_1035": "Veuillez fournir un e-mail valide",
    "CASHIER_12001": "Erreur de transaction de retrait de Weaver",
    "CASHIER_12006": "La demande de retrait a échoué.",
    "CASHIER_1002": "Une erreur interne !",
    "CASHIER_1109": "La validation du joueur a échoué.",
    "CASHIER_1001": "Utilisateur non trouvé",
    "CASHIER_1134": "Option de paiement introuvable pour la devise demandée",
    "CASHIER_1201": "Données introuvables.",
    "CASHIER_2004": "Jeton RMS introuvable",
    "CASHIER_2005": "ID utilisateur Rms introuvable",
    "CASHIER_1111": "URL demandée introuvable",
    "CASHIER_1127": "Veuillez fournir un jeton valide.",
    "CASHIER_2006": "Jeton client invalide",
    "CASHIER_206": "Marchand/alias/domaine non valide trouvé.",
    "CASHIER_4003": "Demande de retrait introuvable",
    "CASHIER_2009": "Veuillez fournir le code PIN de retrait",
    "CASHIER_2010": "Code PIN de retrait invalide",
    "CASHIER_1404": "Demande déjà approuvée",
    "CASHIER_302": "Montant invalide",
    "CASHIER_1209": "Transaction du fournisseur introuvable.",
    "CASHIER_1208": "Transaction utilisateur introuvable.",
    "CASHIER_1022": "Json fourni non valide.",
    "CASHIER_4004": "Erreur de transaction DB",
    "CASHIER_2003": "Erreur lors de l'appel de l'API RMS",
    "CASHIER_1106": "User transaction not found",
    "CASHIER_-1": "Échoué",
    "CASHIER_0": "Succès",

    //WEAVER
    "WEAVER_606": "Nom d'alias invalide",
    "WEAVER_112": "Opération non prise en charge",
    "WEAVER_601": "Domaine invalide",
    "WEAVER_101": "Exception de mise en veille prolongée",
    "WEAVER_543": "Veuillez fournir des détails valides",
    "WEAVER_542": "Les détails ne sont pas fournis.",
    "WEAVER_553": "Une erreur lors du contrôle de validation",
    "WEAVER_102": "Une erreur interne",
    "WEAVER_514": "Le statut du joueur est inactif.",
    "WEAVER_617": "Le joueur n'est pas lié à un système d'ffiliation.",
    "WEAVER_621": "Identifiant d'affilié non fourni",
    "WEAVER_619": "Le joueur n'est pas lié à l'AffiliateId fourni.",
    "WEAVER_620": "Le numéro de mobile est déjà lié à votre compte",
    "WEAVER_533": "L'identifiant RSA d'un joueur particulier n'existe pas",
    "WEAVER_508": "Informations sur le joueur introuvables.",
    "WEAVER_526": "Le paramètre obligatoire est manquant",
    "WEAVER_103": "Requête invalide",
    "WEAVER_802": "Joueur non trouvé",
    "WEAVER_577": "La limite maximale du joueur est dépassée",
    "WEAVER_408": "Ancien mot de passe incorrect",
    "WEAVER_409": "Le mot de passe actuel et le nouveau mot de passe ne peuvent pas être identiques.",
    "WEAVER_410": "Le nouveau mot de passe ne peut pas être du dernier mot de passe",
    "WEAVER_609": "Mot de passe incorrect! Veuillez réessayer!",
    "WEAVER_203": "Joueur non connecté",
    "WEAVER_507": "Trop de données. Veuillez sélectionner plus de filtres",
    "WEAVER_801": "Nom de domaine non valide",
    "WEAVER_522": "Inscription refusée. Veuillez saisir un numéro d'identification RSA valide.",
    "WEAVER_527": "Âge invalide - doit être d'au moins 18 ans",
    "WEAVER_501": "Nom d'utilisateur existe déjà.",
    "WEAVER_503": "Un numéro de portable existe déjà.",
    "WEAVER_564": "Le numéro de mobile et le nom d'utilisateur existent déjà.",
    "WEAVER_502": "L'identifiant de messagerie existe déjà.",
    "WEAVER_565": "L'identifiant de messagerie et le nom d'utilisateur existent déjà.",
    "WEAVER_510": "L’identifiant de messagerie et le numéro de mobile existent déjà.",
    "WEAVER_566": "L'identifiant de messagerie, le numéro de mobile et le nom d'utilisateur existent déjà.",
    "WEAVER_528": "L'identifiant RSA existe déjà.",
    "WEAVER_567": "L'identifiant Rsa et le nom d'utilisateur existent déjà.",
    "WEAVER_534": "RsaId et mobileNo existent",
    "WEAVER_568": "Rsa Id, Mobile Number and User Name already exist.",
    "WEAVER_535": "RsaId et emailId existent",
    "WEAVER_569": "L'identifiant Rsa, l'identifiant de messagerie et le nom d'utilisateur existent déjà.",
    "WEAVER_536": "RsaId, mobileNo et emailId existent",
    "WEAVER_570": "L'identifiant Rsa, l'identifiant de messagerie, le numéro de mobile et le nom d'utilisateur existent déjà.",
    "WEAVER_505": "Le joueur existe déjà avec les mêmes informations.",
    "WEAVER_121": "Devise invalide",
    "WEAVER_2001": "Une erreur interne dans le module de communication, aucun mappage de fournisseur ou d'alias de fournisseur n'existe !",
    "WEAVER_2015": "Une exception Hibernate s'est produite dans le module de communication",
    "WEAVER_106": "Demande de téléchargement de fichier non valide. Seul le contenu en plusieurs parties est autorisé.",
    "WEAVER_415": "Le message a été supprimé.",
    "WEAVER_417": "Aucun message trouvé dans la boîte de réception ID 1234 pour ce joueur",
    "WEAVER_110": "Paramètre(s) de requête non valide(s).",
    "WEAVER_100": "Site en maintenance",
    "WEAVER_111": "Il n’existe aucun détail approprié sur la version de l’application.",
    "WEAVER_0": "Succès",

    //BONUS
    "BONUS_12204": "Aucun alias actif trouvé.",
    "BONUS_12101": "Domaine invalide trouvé.",
    "BONUS_12411": "Veuillez fournir une communication valide",
    "BONUS_12433": "Dépassement de la limite de dépôt Anon",
    "BONUS_12413": "Veuillez fournir un identifiant de joueur valide",
    "BONUS_12303": "Veuillez fournir un fournisseur valide.",
    "BONUS_12301": "Veuillez fournir un service valide.",
    "BONUS_12302": "Veuillez fournir un jeu valide.",
    "BONUS_12051": "Données introuvables.",
    "BONUS_12052": "Marchand non valide trouvé.",
    "BONUS_12008": "JSON invalide trouvé.",
    "BONUS_12432": "Erreur dans la vente au détaillant",
    "BONUS_12423": "Erreur lors de l'appel de l'API Ram",
    "BONUS_12151": "Utilisateur invalide trouvé.",
    "BONUS_12434": "Erreur lors de l'obtention du code Qr",
    "BONUS_12428": "ERREUR au niveau du crédit du portefeuille Weaver",
    "BONUS_12414": "Le nombre total d'utilisations dépasse le nombre maximal d'utilisations",
    "BONUS_12426": "Jeton RMS manquant",
    "BONUS_12431": "ID utilisateur Rms introuvable",
    "BONUS_12009": "URL demandée introuvable",
    "BONUS_12010": "Veuillez fournir un jeton valide",
    "BONUS_12430": "Jeton client invalide",
    "BONUS_12429": "Réponse invalide trouvée à partir de RMS",
    "BONUS_-1": "Échoué",
    "BONUS_0": "Succès",
    "BONUS_1": "Une erreur inconnue s'est produite, veuillez réessayer.",

    //IGE
    "IGE_401": "Ce n'est pas une demande valide.",
    "IGE_402": "L’arrière-plan n’est pas disponible pour la résolution d’écran donnée.",
    "IGE_403": "Les ressources ne sont pas disponibles pour la résolution d’écran donnée.",
    "IGE_404": "Les éléments du panneau ne sont pas disponibles pour la résolution d'écran donnée.",
    "IGE_405": "Une erreur s'est produite. Veuillez réessayer.",
    "IGE_406": "Aucun jeu disponible.",
    "IGE_407": "Une erreur interne",
    "IGE_408": "Veuillez fournir la valeur du paramètre appropriée.",
    "IGE_409": "Veuillez demander un jeu valide",
    "IGE_410": "Le jeu n'existe pas pour mobile. Veuillez jouer au jeu sur PC.",
    "IGE_411": "Veuillez fournir la valeur du paramètre appropriée.",
    "IGE_412": "Les informations sur les billets n'existent pas",
    "IGE_02": "Une erreur s'est produite. Veuillez réessayer.",
    "IGE_03": "Une erreur s'est produite. Veuillez réessayer.",
    "IGE_04": "Votre demande a expiré.",
    "IGE_06": "Demande de téléchargement de fichier non valide. Seul le contenu en plusieurs parties est autorisé.",
    "IGE_07": "Type d'appareil non fourni.",
    "IGE_08": "Type d'agent utilisateur non fourni.",
    "IGE_10": "Paramètre(s) de requête non valide(s).",
    "IGE_11": "Aucun Enregistrement Trouvé",
    "IGE_12": "Une erreur s'est produite. Veuillez réessayer.",
    "IGE_201": "Une erreur s'est produite. Veuillez réessayer.",
    "IGE_202": "Identifiant de session invalide",
    "IGE_203": "Joueur non connecté",
    "IGE_204": "Code de service invalide",
    "IGE_205": "Montant invalide",
    "IGE_206": "Joueur invalide",
    "IGE_207": "Fournisseur non authentique",
    "IGE_208": "Identifiants de fournisseur invalides",
    "IGE_209": "Solde de joueur insuffisant",
    "IGE_210": "Votre transaction a été temporairement bloquée",
    "IGE_211": "Incohérence dans l'équilibre des utilisateurs.",
    "IGE_212": "Type de portefeuille invalide.",
    "IGE_213": "Sous-portefeuille invalide",
    "IGE_214": "Type de solde invalide.",
    "IGE_215": "Solde insuffisant pour débiter le compte joueur.",
    "IGE_216": "Transaction en double",
    "IGE_217": "Le retrait a déjà été annulé.",
    "IGE_218": "Le retrait ne peut pas être annulé, déjà traité",
    "IGE_219": "Billets insuffisants.",
    "IGE_220": "Aucun appareil trouvé mappé avec l'adresse Mac donnée",
    "IGE_221": "Identifiant de transaction invalide",
    "IGE_222": "Cette transaction a déjà été traitée",
    "IGE_100": "Erreur lors de l'achat du jeu, veuillez réessayer.",
    "IGE_0": "Succès",
    "IGE_1": "Problème inattendu",
    "IGE_2": "Identifiant de transaction en double",
    "IGE_3": "Fonds insuffisants",
    "IGE_4": "Paramètres d'entrée invalides",
    "IGE_5": "Jeton invalide",
    "IGE_6": "Montant de rollback différent du montant initial (lors du remboursement)",
    "IGE_7": "Jeton expiré",
    "IGE_8": "Utilisateur non trouvé",
    "IGE_9": "les informations d'identification invalides",
    "IGE_7332": "Solde insuffisant",
    "IGE_7333": "Veuillez vous connecter à Internet et réessayer !",
    "IGE_7335": "Désolé pour le dérangement, veuillez réessayer",
    "IGE_7530": "Données incomplètes",
    "IGE_-1": "Une erreur s'est produite",
    "IGE_7338": "Une erreur s'est produite. Veuillez réessayer!",
    "IGE_8205": "À venir...",
    "IGE_7444": "Erreur de serveur, veuillez réessayer plus tard",
    "IGE_645": "Tous les billets sont épuisés",
    "IGE_876": "Nous avons détecté un réseau lent, cela peut prendre plus de temps que d'habitude.",
    "IGE_226": "La transaction a déjà été traitée avec ce refTxnNo",
    "IGE_111": "Le jeu est déjà terminé",
    "IGE_1002": "Code de devise invalide",
    "IGE_1003": "Aucune donnée disponible",
    "IGE_1004": "Code de langue invalide",
    "IGE_500": "Erreur interne du serveur",
    "IGE_1005": "La transaction est toujours en cours, veuillez vérifier après un certain temps",
    "IGE_115": "Erreur de connexion",

    //DGE
    "DGE_0": "Succès",
    "DGE_1": "mauvaise signature",
    "DGE_602": "Utilisateur de service non authentique",
    "DGE_102": "Une erreur interne",
    "DGE_704": "Signature introuvable dans la demande",
    "DGE_606": "Nom d'alias invalide",
    "DGE_220": "Cet appareil n'est pas enregistré",
    "DGE_101": "Exception de mise en veille prolongée",
    "DGE_203": "Joueur non connecté",
    "DGE_206": "Joueur invalide",
    "DGE_210": "Votre transaction a été temporairement bloquée",
    "DGE_609": "Mot de passe incorrect! Veuillez réessayer!",
    "DGE_405": "L'utilisateur n'est pas valide !",
    "DGE_205": "Montant invalide",
    "DGE_216": "Transaction en double",
    "DGE_212": "Type de portefeuille invalide",
    "DGE_214": "Type de solde invalide",
    "DGE_121": "Devise invalide",
    "DGE_201": "Requête invalide",
    "DGE_514": "Le statut du joueur est inactif",
    "DGE_420": "ID de joueur invalide",
    "DGE_209": "Solde de joueur insuffisant !!",
    "DGE_1001": "Erreur système interne !!",
    "DGE_1002": "Vente de ces nombreux tirages interdite",
    "DGE_1003": "Les données des tirages et le nombre de tirages ne sont pas égaux",
    "DGE_1004": "Limite maximale de sélection de tirages atteinte",
    "DGE_1005": "Données de panneau non valides fournies !",
    "DGE_1006": "Type de pari sélectionné non valide !",
    "DGE_1007": "Type de sélection non valide sélectionné !",
    "DGE_1008": "Configuration de sélection non valide sélectionnée !",
    "DGE_1009": "Le nombre total de valeurs sélectionnées n'est pas correct !",
    "DGE_1010": "Nombre de panneaux sélectionnés supérieur à la limite maximale de panneaux",
    "DGE_1011": "Code de jeu fourni non valide",
    "DGE_1012": "Valeurs sélectionnées dépassant la plage",
    "DGE_1013": "Le marchand n'existe pas !",
    "DGE_1014": "Mot de passe incorrect !",
    "DGE_1015": "Multiple de montant de pari non valide fourni",
    "DGE_1016": "Tirage non disponible !",
    "DGE_1017": "Valeurs sélectionnées non valides !",
    "DGE_1018": "Données JSON non valides fournies",
    "DGE_1019": "Limite d'achat quotidienne du joueur atteinte",
    "DGE_1020": "Nom d'alias fourni non valide",
    "DGE_1021": "Adresse Mac fournie non valide",
    "DGE_1022": "Identifiant d'utilisateur fourni non valide",
    "DGE_1023": "Code de devise fourni non valide",
    "DGE_1024": "Aucun billet pour ce tirage",
    "DGE_1025": "Impossible de récupérer les données du joueur !",
    "DGE_1026": "La transaction a échoué !",
    "DGE_1027": "Impossible de pousser Winning vers le marchand !",
    "DGE_1028": "La confirmation du pari a échoué !",
    "DGE_1029": "Le remboursement du pari a échoué !",
    "DGE_1030": "Tirage au sort pour ce jeu introuvable",
    "DGE_1031": "La distribution des prix ne peut pas être effectuée !",
    "DGE_1032": "Erreur lors de la récupération des billets gagnants",
    "DGE_1033": "Données de tirage invalides !",
    "DGE_1034": "Aucune transaction trouvée !",
    "DGE_1035": "mauvais numéro de billet !",
    "DGE_1036": "contactez l'équipe commerciale !",
    "DGE_1037": "Le système ne prend pas en charge la devise",
    "DGE_1038": "Erreur de devise : Veuillez vous connecter à l'administrateur !",
    "DGE_1039": "Aucun montant reporté lors du tirage précédent !",
    "DGE_1040": "Aucun RSR reporté lors du tirage précédent !",
    "DGE_1043": "Le tirage ne peut pas être effectué !",
    "DGE_1049": "Nom d'utilisateur fourni non valide",
    "DGE_1050": "Impossible de récupérer les données du détaillant !",
    "DGE_1051": "Format du numéro gagnant invalide !",
    "DGE_1053": "Ce billet ne peut pas être réclamé chez ce détaillant !",
    "DGE_1054": "Erreur dans le cryptage du ticket",
    "DGE_1055": "Jeu marchand invalide !",
    "DGE_1056": "Impossible de réclamer en tant que portefeuille en type push automatique !",
    "DGE_1057": "Nombre de lignes invalide !",
    "DGE_1058": "Numéro choisi invalide !",
    "DGE_1059": "Impossible d'effectuer PayPwt !",
    "DGE_1060": "Billet déjà réclamé !",
    "DGE_1061": "Canal d'achat invalide",
    "DGE_1062": "Limite de réimpression dépassée",
    "DGE_1063": "La demande ne peut pas être authentifiée !",
    "DGE_1064": "Impossible d'annuler le billet",
    "DGE_1065": "billet déjà annulé !",
    "DGE_1066": "Mode QP invalide",
    "DGE_1067": "Paramètre QP non valide",
    "DGE_1068": "Échec du remboursement de la réconciliation !",
    "DGE_1069": "Erreur lors de la génération du code de validation",
    "DGE_1070": "le nombre total n'est pas correct",
    "DGE_1071": "Identifiant de transaction marchand invalide",
    "DGE_1072": "ne peut pas geler",
    "DGE_1073": "Erreur lors de la suppression du planificateur.",
    "DGE_1074": "Combinaison non valide d'identifiant de joueur et de transaction marchande pour le code marchand",
    "DGE_1075": "La valeur sélectionnée n'a pas le format/longueur de valeur d'entrée approprié",
    "DGE_1076": "Type d'appareil d'achat invalide !!",
    "DGE_1077": "Tirage invalide !",
    "DGE_1078": "Revendeur non autorisé pour ce billet !",
    "DGE_1079": "Le billet a une réimpression !",
    "DGE_1080": "Billet excédentaire vendu par détaillant !",
    "DGE_1081": "Échec de la réimpression du dessin effectué",
    "DGE_1082": "Mauvais statut PWT",
    "DGE_1083": "Le billet B2C ne peut pas être annulé",
    "DGE_1084": "La vente est actuellement arrêtée par l'administrateur !",
    "DGE_1085": "Le nom d'utilisateur ou l'ID de session ne peuvent pas être nuls",
    "DGE_1086": "Impossible de demander une API tierce !",
    "DGE_1087": "Le type de partie à la réclamation ne peut pas être nul",
    "DGE_1088": "Le type d'interface ne peut pas être nul",
    "DGE_1089": "La vente au marchand ne peut pas être nulle",
    "DGE_1090": "Le code de vérification ne peut pas être nul",
    "DGE_1091": "Le nom d'utilisateur ne peut pas être nul",
    "DGE_1092": "L'identifiant de session ne peut pas être nul",
    "DGE_1093": "L'identifiant de la partie à la réclamation ne peut pas être nul.",
    "DGE_1094": "Statut de tirage invalide",
    "DGE_1095": "Jour de la semaine demandé non valide",
    "DGE_1096": "Index de chaîne invalide",
    "DGE_1097": "Index d'état de format non valide",
    "DGE_1098": "Index des types de parties non valide",
    "DGE_1099": "Nom du type de partie non valide",
    "DGE_1100": "Index modifiable de propriété non valide",
    "DGE_1101": "Index de statut de propriété invalide",
    "DGE_1102": "Code de vérification de billet invalide",
    "DGE_1103": "Le tirage ne peut pas être annulé",
    "DGE_1107": "Tirage non disponible",
    "DGE_1108": "Soumission d'un résultat invalide pour le jeu",
    "DGE_1104": "le billet promotionnel/taffel ne peut pas être annulé",
    "DGE_1105": "Date invalide",
    "DGE_1106": "Le commerçant n'est pas autorisé à la vente !!",
    "DGE_1109": "Montant de pari multiple fourni non valide.",
    "DGE_1110": "le billet promotionnel/taffel ne peut pas être réimprimé directement",
    "DGE_1111": "Numéro de billet invalide",
    "DGE_1112": "ID de jeu invalide",
    "DGE_1113": "Date de début invalide !",
    "DGE_1114": "Date de fin invalide !",
    "DGE_1115": "La date de début ne peut pas être supérieure à la date de fin !",
    "DGE_1116": "Code de famille invalide",
    "DGE_1117": "Mode de victoire invalide",
    "DGE_1118": "impossible de modifier le temps de gel",
    "DGE_1119": "impossible de modifier l'heure d'arrêt de la vente",
    "DGE_1120": "impossible de modifier l'heure d'exécution de la vente",
    "DGE_1121": "QP non autorisé !",
    "DGE_1122": "Chaîne d'annulation invalide !",
    "DGE_1123": "Type d'annulation automatique invalide !",
    "DGE_1124": "Opération invalide",
    "DGE_1125": "L'événement multiplicateur de prix de tirage a échoué.",
    "DGE_1126": "Paramètre de demande d'annulation automatique non valide",
    "DGE_1127": "Erreur de fonctionnement de la base de données dans le ticket d'achat",
    "DGE_1128": "ne peut pas modifier l'heure de vérification",
    "DGE_1129": "impossible de modifier l'heure de fin de la réclamation",
    "DGE_1130": "impossible de modifier l'heure de début de la réclamation",
    "DGE_1215": "La vente n'a pas encore commencé. S'il vous plaît, attendez encore un peu !",
    "DGE_12345": "Expiration du délai du serveur",
    "DGE_1201": "Limite atteinte",
    "DGE_596": "Pari non autorisé pour le jeu",
    "DGE_2013": "La dalle max a été atteinte !",

    //RAM
    "RAM_0" : "Succès",
    "RAM_10353": "Alias invalide trouvé.",
    "RAM_10106": "Veuillez fournir un numéro de mobile valide",
    "RAM_10107": "Veuillez fournir un e-mail valide",
    "RAM_10006": "Format non valide trouvé pour ##@@##",
    "RAM_10008": "JSON invalide trouvé.",
    "RAM_10009": "URL demandée introuvable",
    "RAM_10012": "Réponse invalide trouvée lors de la communication",
    "RAM_10302": "L'e-mail existe déjà.",
    "RAM_10575": "Veuillez fournir un type valide pour l'e-mail ou le SMS.",
    "RAM_10514": "Vous n'êtes pas autorisé à effectuer cette action.",
    "RAM_10549": "Inscription non autorisée pour un identifiant RSA donné.",
    "RAM_10004": "Veuillez fournir un ##@@## valide",
    "RAM_10454": "L'OTP saisi est expiré. Veuillez réessayer.",
    "RAM_10455": "Veuillez fournir une date valide.",
    "RAM_10453": "Échec de la vérification OTP.",
    "RAM_10452": "Le joueur existe déjà.",
    "RAM_10457": "Veuillez fournir une URL d'enregistrement de joueur valide.",
    "RAM_10459": "Quelque chose c'est mal passé. Merci d'essayer plus tard.",
    "RAM_10571": "Veuillez fournir un identifiant RSA de joueur valide.",
    "RAM_10523": "Veuillez fournir un identifiant principal de joueur valide.",
    "RAM_10308": "Veuillez entrer un mobile/e-mail valide",
    "RAM_406": "Le nom d'utilisateur ou le mot de passe n'est pas valide",
    "RAM_10567": "Le joueur est bloqué. Veuillez contacter l'administrateur.",
    "RAM_10201": "Domaine invalide trouvé.",
    "RAM_10531": "Fournissez uniquement DomainId ou MerchantDoaminId",
    "RAM_10536": "Nombre de demandes de mise à jour de profil atteint.",
    "RAM_10491": "Joueur invalide trouvé.",
    "RAM_10526": "Statut du profil du joueur déjà le même que celui demandé",
    "RAM_10540": "Veuillez d'abord mettre à jour l'identifiant Rsa.",
    "RAM_10538": "Le profil du joueur doit être actif pour désactiver son profil.",
    "RAM_10518": "Vérification en attente pour le nom de téléphone mobile ou la question de sécurité du joueur.",
    "RAM_10519": "Certains documents de joueurs ne sont pas encore vérifiés",
    "RAM_10520": "Le lecteur n'a pas de document actif pour tous les doctypes actifs",
    "RAM_10539": "Le joueur doit télécharger des documents pour l'activation du profil.",
    "RAM_10495": "Informations de base du joueur introuvables.",
    "RAM_10585": "Votre numéro de portable est trouvé en double chez certains joueurs.",
    "RAM_10310": "Veuillez contacter le service client pour modifier votre numéro de mobile.",
    "RAM_10497": "Champs de coordonnées bancaires invalides.",
    "RAM_10546": "Veuillez fournir un document valide",
    "RAM_10496": "Aucun jour d'expiration présent pour le type de modification demandé.",
    "RAM_10492": "Statut non valide trouvé dans les configurations."

  };

}